#!/usr/bin/env bash
# Install nginx on your web-01
sudo apt-get update -y
sudo apt-get install nginx ufw -y
sudo ufw allow ssh
sudo ufw allow 'Nginx Full'
sudo ufw enable
echo "Hello World!" > /var/www/html/index.html
service nginx start
