#!/usr/bin/env bash
# Edit file with SED to redirect a 301
sudo apt-get update -y
sudo apt-get install -y nginx
sudo touch /var/www/html/index.html
sudo echo "Hello World!" |  /var/www/html/index.html
sudo printf %s "server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}" | /etc/nginx/sites-available/default
sudo service nginx restart
