#!/usr/bin/env bash
# Edit file with SED to redirect a 301
apt-get update -y
apt-get install -y nginx
sudo nano /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
sudo nano /usr/share/nginx/html/custom_404.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
printf %s "server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /etc/nginx/html;
	index index.html index.htm index.nginx-debian.html;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4
	}
	
	error_page 404 /custom_404.html;
	location = /custom_404.html {
		root /usr/share/nginx/html;
		internal;
	}

}" > /etc/nginx/sites-available/default
service nginx reload
