#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server
add-apt-repository ppa:vbernat/haproxy-1.5 -y
apt-get update -y 
apt-get dist-upgrade -y 
apt-get install haproxy -y
echo -e "\nfrontend http\n\tbind *:80\n\tdefault_backend web_backend\n\nbackend web_backend\n\tbalance roundrobin\n\tserver web-01 34.202.158.152:80\n\tserver web-02 100.25.34.22:80" >> /etc/haproxy/haproxy.cfg
service haproxy restart
