#!/usr/bin/env bash
# uninstall apache and install nginx and make it listen on port 80
sudo service apache2 stop
sudo apt remove apache2.*
sudo apt-get update
sudo apt-get install nginx
sed -i "s/80/8080/g" /etc/nginx/sies-available/default
sudo service nginx restart
