#!/usr/bin/env bash
#Write a Bash script that displays
#The content of the current directory
while IFS=':' read -r username password uid gid info home shell
do
	echo "The user $username is part of the $gid gang,"\
	"lives in $home and rides $shell."\
	"$uid's place is protected by the passcode $password,"\
       	"more info about the user : $uid $info"
done < "/etc/passwd"
