#!/usr/bin/env bash
#Write a Bash script that gives
#you information about the school file
if [ -e ./school ]
then
	echo "school file exists"
	if ! [ -s ./school ]
	then
		echo "school file is empty"
		if [ -f ./school ]
		then
			echo "school is a regular file" 
		fi
	else
		echo "school file is not empty"
		if [ -f ./school ]
		then
			echo "school is a regular file"
		fi
	fi
else
	echo "school file does not exist"
fi
