#!/usr/bin/env bash
#change ip address
cp /etc/hosts ~/hosts.new
echo "^127.0.0.2( |\t){1,10}localhost( |\t){0,10}$" > ~/hosts.new 
echo "8.8.8.8 facebook.com" > ~/hosts.new
cp -f ~/hosts.new /etc/hosts
