#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user.
sudo adduser --system --no-create-home --shell /bin/false --group --disabled-login nginx
sed -i "s/user www-data;/user nginx;" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo service nginx restart
