#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user.
sudo adduser --system --no-create-home --shell /bin/false --group --disabled-login nginx
sudo sed -i '1i user nginx;' /etc/nginx/nginx.conf
sudo sed -i 's/\<80\>/&80' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo service nginx restart
